version: '3.8'

services:
  web:
    build: .
    container_name: java_web_app_container
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: weatherApplicationDataBase
      DB_USER: postgres
      DB_PASSWORD: admin
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres_container
    environment:
      POSTGRES_DB: weatherApplicationDataBase
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
